### ISSUE TITLE
how to get started

### ISSUE THREAD

**Issue by hsunami** [mongoid/kiqstand#1]
Hi,

First of all, thank you so much for implementing kiqstand.

Secondly, I'm a beginner with mongoid, but am doing some heavy tracking, so I prefer to have async writes to mongodb using sidekiq. 

Could you give a simple example on how to use kiqstand with mongoid?

Thanks,
Jeff

**Comment by durran** [comment]
It's the same as you would use sidekiq normally, you just need to add the middleware as per the README. For example if you had a Mongoid document called `User` and needed to do some long task in a worker:

``` ruby
class UserWorker
  include Sidekiq::Worker

  def perform(id)
    User.find(id).do_some_long_method
  end
end
```

Then to call it:

``` ruby
UserWorker.perform_async(user.id)
```

**Comment by hsunami** [comment]
Thanks for your help, Durran. I really appreciate it.
