### ISSUE TITLE
Cannot install kiqstand with mongoid 4.0.0.beta1

### ISSUE THREAD

**Issue by donnykurnia** [mongoid/kiqstand#11]
My client using mongoid 4.0.0.beta1 and I want to add sidekiq When I run `bundle install`:

```
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...........
Bundler could not find compatible versions for gem "mongoid":
  In Gemfile:
    kiqstand (>= 0) ruby depends on
      mongoid (~> 3.0) ruby

    mongoid (4.0.0.beta1)
```

When will the new version released for both mongoid and kiqstand?

**Comment by arthurnn** [comment]
you dont need `kiqstand` on mongoid 4+ .. just remove it from your gem file, and it should be good

**Comment by donnykurnia** [comment]
Ok, thanks.

**Comment by geoffw8** [comment]
All doesn't seem to be good my end, I keep getting Timeout/Warning errors:

2014-07-28T15:39:02.514Z 6259 TID-1gka6w WARN: {"retry"=>true, "queue"=>"person_processor", "class"=>"PersonProcessor", "args"=>[{"client_id"=>{"$oid"=>"53bfea9d736572511a0
00000"}, "list_id"=>"53d61b797261690dc2000000"}, "membershipnumber"], "jid"=>"0520152cfdb4cdbe874b61ca", "enqueued_at"=>1406543798.321959, "error_message"=>"Waited 0.5 sec", "error_class"=

> "Timeout::Error", "failed_at"=>1406561942.3811984, "retry_count"=>0}
> 2014-07-28T15:39:02.592Z 6259 TID-1gka6w WARN: Waited 0.5 sec
> 2014-07-28T15:39:02.592Z 6259 TID-1gka6w WARN: /home/vagrant/.rvm/gems/ruby-2.0.0-p353@communicate/gems/connection_pool-2.0.0/lib/connection_pool/timed_stack.rb:42:in `bloc
> k (2 levels) in pop'
> /home/vagrant/.rvm/gems/ruby-2.0.0-p353@communicate/gems/connection_pool-2.0.0/lib/connection_pool/timed_stack.rb:34:in`loop'
> /home/vagrant/.rvm/gems/ruby-2.0.0-p353@communicate/gems/connection_pool-2.0.0/lib/connection_pool/timed_stack.rb:34:in `block in pop'
> /home/vagrant/.rvm/gems/ruby-2.0.0-p353@communicate/gems/connection_pool-2.0.0/lib/connection_pool/timed_stack.rb:33:in`synchronize'
> /home/vagrant/.rvm/gems/ruby-2.0.0-p353@communicate/gems/connection_pool-2.0.0/lib/connection_pool/timed_stack.rb:33:in `pop'
> /home/vagrant/.rvm/gems/ruby-2.0.0-p353@communicate/gems/connection_pool-2.0.0/lib/connection_pool.rb:69:in`checkout'
> /home/vagrant/.rvm/gems/ruby-2.0.0-p353@communicate/gems/connection_pool-2.0.0/lib/connection_pool.rb:56:in `with'

**Comment by hapiben** [comment]
Hi @geoffw8, do you still have this issue?

**Comment by geoffw8** [comment]
Hi @benedictaluan 

Yes I do actually. I've wanted to spend more time on it but I've been flat out unfortunately.

How comes?
