### ISSUE TITLE
kiqstand not compatible with mongoid 4.0

### ISSUE THREAD

**Issue by beingmattlevy** [mongoid/kiqstand#12]
Bundler could not find compatible versions for gem "mongoid":
  In Gemfile:
    kiqstand (>= 0) ruby depends on
      mongoid (~> 3.0) ruby

```
mongoid (4.0.0)
```

**Comment by arthurnn** [comment]
kiqstand is not necessary for mongoid 4.x

**Comment by beingmattlevy** [comment]
Aces! Thanks!
