### ISSUE TITLE
general inquiry, not issue

### ISSUE THREAD

**Issue by kateorade44** [mongoid/kiqstand#13]
Is it only Mongoid 4 that is exempt from requiring kiqstand, or any later Mongoid versions (like 5) as well? Not sure if there is a separate project or not so master may not be latest version in this case. Thanks for your help.

**Comment by dblock** [comment]
Looks like this project hasn't been maintained for years. If someone wants to take a stab at adding tests/compatibility for mongoid newer versions go for it!

**Comment by durran** [comment]
Mongoid versions 5+ will not require this gem, as the connection pool behaviour is baked into the core ruby driver. The reason for this gem initially was that Moped was assuming 1 connection per thread and the middleware needed to disconnect all connections with each new request from a worker.

**Comment by kateorade44** [comment]
Awesome, that's what we thought - thanks guys!

**Comment by durran** [comment]
np
