### ISSUE TITLE
Redis::CannotConnectError at /sidekiq/ 

### ISSUE THREAD

**Issue by xxswingxx** [mongoid/kiqstand#2]
Hi thanks for developing this gem but I have the following problem:

As the wiki points I have an initializer with:

``` ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    debugger
    chain.add Kiqstand::Middleware
  end
end
```

But when I try to run a perform_async or go the sideqik monitor page I get:

Redis::CannotConnectError at /sidekiq/
Error connecting to Redis on localhost:6379 (ECONNREFUSED)

Due the freshness of this gem I couldn't find many examples so I'm not sure what is happening. Thank you again.

**Comment by durran** [comment]
Kiqstand does not have anything to do with the connecting to Redis, so the issue would not be here but in Sidekiq if it is an issue. But what I would check is:
1. Is Redis not running (`redis-server`)?
2. If your Redis is not running on localhost you would need to tell Sidekiq where it is.

``` ruby
Sidekiq.configure_server do |config|
  config.redis = { :namespace => 'sidekiq', :url => "redis://#{redis_host}" }
end
```

**Comment by xxswingxx** [comment]
Yes the problem was Redis server was not running. I think I missunderstood how kiqstand works, thanks.
