### ISSUE TITLE
Rails 4 + Mongoid

### ISSUE THREAD

**Issue by lucasgertel** [mongoid/kiqstand#5]
Hello @durran 
I'm not sure why it's not working for me.

Trying to use:
gem 'mongoid', github: 'mongoid/mongoid'
gem 'kiqstand', github: 'mongoid/kiqstand'

Got:
Bundler could not find compatible versions for gem "mongoid":
  In Gemfile:
    kiqstand (>= 0) ruby depends on
      mongoid (~> 3.0) ruby

```
mongoid (4.0.0)
```

**Comment by durran** [comment]
Kiqstand is not needed nor will be necessary with Mongoid 4 as it introduced conncection pooling and we don't to explicitly close connections anymore. Simply adjust your `pool_size` option as necessary.
